export type FundingInvestor = {
  name: string;
  type: "VC" | "Angel" | "Grant" | "Accelerator";
  location: "Local" | "Regional" | "National" | "International";
  scope: "US" | "Africa" | "Europe" | "Asia" | "Global";
  thesis: string;
  checkSize: string;
  stage: string;
  website: string;
};

/** Curated directory (illustrative; verify terms before outreach). */
export const FUNDING_INVESTORS: FundingInvestor[] = [
  {
    name: "Y Combinator",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "B2B SaaS, consumer, fintech, climate; intensive 3-month batch.",
    checkSize: "$500K–$125K standard deal (varies)",
    stage: "Pre-seed, Seed",
    website: "https://www.ycombinator.com",
  },
  {
    name: "Techstars",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "Sector-agnostic; mentorship-heavy accelerators worldwide.",
    checkSize: "$120K–$220K typical",
    stage: "Pre-seed",
    website: "https://www.techstars.com",
  },
  {
    name: "500 Global",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "High-volume seed investing + accelerator programs.",
    checkSize: "$150K seed checks (program-dependent)",
    stage: "Pre-seed, Seed",
    website: "https://500.co",
  },
  {
    name: "Sequoia Capital",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Iconic growth; software, fintech, healthcare, consumer.",
    checkSize: "$1M–$100M+",
    stage: "Seed through late stage",
    website: "https://www.sequoiacap.com",
  },
  {
    name: "Andreessen Horowitz (a16z)",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Software eating the world; crypto, bio, fintech sub-funds.",
    checkSize: "$500K–$50M+",
    stage: "Seed to growth",
    website: "https://a16z.com",
  },
  {
    name: "Accel",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Early-stage and growth; strong in SaaS and infrastructure.",
    checkSize: "$500K–$50M",
    stage: "Seed, Series A–C",
    website: "https://www.accel.com",
  },
  {
    name: "Index Ventures",
    type: "VC",
    location: "International",
    scope: "Europe",
    thesis: "Consumer, fintech, AI, enterprise across London/SF.",
    checkSize: "$1M–$40M",
    stage: "Seed to Series C",
    website: "https://www.indexventures.com",
  },
  {
    name: "NEA",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Healthcare, technology, energy; multi-stage.",
    checkSize: "$2M–$40M",
    stage: "Early to growth",
    website: "https://www.nea.com",
  },
  {
    name: "Bessemer Venture Partners",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Cloud, healthcare, consumer; long-horizon SaaS.",
    checkSize: "$1M–$35M",
    stage: "Seed through growth",
    website: "https://www.bvp.com",
  },
  {
    name: "General Catalyst",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Enterprise, fintech, healthcare, climate.",
    checkSize: "$1M–$50M",
    stage: "Seed to growth",
    website: "https://www.generalcatalyst.com",
  },
  {
    name: "Khosla Ventures",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Bold tech; sustainability, AI, healthcare.",
    checkSize: "$500K–$25M",
    stage: "Seed to Series B",
    website: "https://www.khoslaventures.com",
  },
  {
    name: "Founders Fund",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Contrarian bets; aerospace, bio, deep tech.",
    checkSize: "$500K–$50M",
    stage: "Seed to growth",
    website: "https://foundersfund.com",
  },
  {
    name: "Greylock Partners",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Enterprise, infrastructure, consumer at scale.",
    checkSize: "$1M–$40M",
    stage: "Seed to Series C",
    website: "https://greylock.com",
  },
  {
    name: "Lightspeed Venture Partners",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Enterprise, consumer, fintech; India/SEA strong.",
    checkSize: "$1M–$50M",
    stage: "Seed to growth",
    website: "https://lsvp.com",
  },
  {
    name: "Insight Partners",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Scale-up software; growth equity.",
    checkSize: "$10M–$500M",
    stage: "Series B+",
    website: "https://www.insightpartners.com",
  },
  {
    name: "Tiger Global",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "High-velocity growth rounds; consumer internet.",
    checkSize: "$5M–$100M+",
    stage: "Series A–D",
    website: "https://www.tigerglobal.com",
  },
  {
    name: "SoftBank Vision Fund",
    type: "VC",
    location: "International",
    scope: "Asia",
    thesis: "Large checks; AI, robotics, mobility, commerce.",
    checkSize: "$50M–$500M+",
    stage: "Growth",
    website: "https://group.softbank/en/visionfund",
  },
  {
    name: "Partech Africa",
    type: "VC",
    location: "Regional",
    scope: "Africa",
    thesis: "Tech-enabled services, fintech, commerce across Africa.",
    checkSize: "$500K–$15M",
    stage: "Seed, Series A",
    website: "https://partechafrica.com",
  },
  {
    name: "TLcom Capital",
    type: "VC",
    location: "Regional",
    scope: "Africa",
    thesis: "Sub-Saharan tech; fintech, edtech, health.",
    checkSize: "$1M–$10M",
    stage: "Series A–B",
    website: "https://tlcomcapital.com",
  },
  {
    name: "EchoVC Partners",
    type: "VC",
    location: "Regional",
    scope: "Africa",
    thesis: "Underserved markets; consumer, media, fintech.",
    checkSize: "$250K–$3M",
    stage: "Seed, Series A",
    website: "https://echovc.com",
  },
  {
    name: "CRE Venture Capital",
    type: "VC",
    location: "Regional",
    scope: "Africa",
    thesis: "East & Southern Africa; enterprise software, fintech.",
    checkSize: "$500K–$5M",
    stage: "Seed to A",
    website: "https://cre.vc",
  },
  {
    name: "Launch Africa Ventures",
    type: "VC",
    location: "Regional",
    scope: "Africa",
    thesis: "Pan-African seed fund; B2B marketplaces, SaaS.",
    checkSize: "$100K–$1M",
    stage: "Pre-seed, Seed",
    website: "https://launchafrica.vc",
  },
  {
    name: "Ingressive Capital",
    type: "VC",
    location: "Regional",
    scope: "Africa",
    thesis: "Nigeria-focused seed; developer tools, fintech.",
    checkSize: "$200K–$500K",
    stage: "Pre-seed, Seed",
    website: "https://ingressivecapital.com",
  },
  {
    name: "Flat6Labs",
    type: "Accelerator",
    location: "Regional",
    scope: "Africa",
    thesis: "MENA accelerators; early traction and follow-on.",
    checkSize: "$50K–$200K",
    stage: "Pre-seed",
    website: "https://www.flat6labs.com",
  },
  {
    name: "Seedstars Africa",
    type: "Accelerator",
    location: "Regional",
    scope: "Africa",
    thesis: "Emerging market acceleration; education, health.",
    checkSize: "$50K–$250K",
    stage: "Pre-seed",
    website: "https://seedstars.com",
  },
  {
    name: "Atomico",
    type: "VC",
    location: "International",
    scope: "Europe",
    thesis: "European tech champions; climate, deep tech.",
    checkSize: "$3M–$50M",
    stage: "Series A–C",
    website: "https://atomico.com",
  },
  {
    name: "Northzone",
    type: "VC",
    location: "International",
    scope: "Europe",
    thesis: "Nordic/UK; fintech, health, software.",
    checkSize: "$1M–$25M",
    stage: "Seed to B",
    website: "https://www.northzone.com",
  },
  {
    name: "Balderton Capital",
    type: "VC",
    location: "International",
    scope: "Europe",
    thesis: "European Series A specialist.",
    checkSize: "$3M–$25M",
    stage: "Series A–B",
    website: "https://www.balderton.com",
  },
  {
    name: "Sequoia China / HongShan",
    type: "VC",
    location: "International",
    scope: "Asia",
    thesis: "China tech leaders; consumer, enterprise.",
    checkSize: "$5M–$100M",
    stage: "Growth",
    website: "https://www.hongshan.com",
  },
  {
    name: "SoftBank Asia Ventures",
    type: "VC",
    location: "International",
    scope: "Asia",
    thesis: "India/SEA growth; consumer internet.",
    checkSize: "$10M–$80M",
    stage: "Series B+",
    website: "https://group.softbank",
  },
  {
    name: "Peak XV Partners",
    type: "VC",
    location: "International",
    scope: "Asia",
    thesis: "India/Southeast Asia; SaaS, fintech, consumer.",
    checkSize: "$2M–$40M",
    stage: "Seed to C",
    website: "https://peakxv.com",
  },
  {
    name: "Antler",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "Co-founder matching + pre-seed in many cities.",
    checkSize: "$100K–$250K",
    stage: "Pre-seed",
    website: "https://www.antler.co",
  },
  {
    name: "Entrepreneur First (EF)",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "Talent-first; deep tech and ambitious founders.",
    checkSize: "$100K–$250K",
    stage: "Pre-seed",
    website: "https://www.joinef.com",
  },
  {
    name: "SBIR / STTR (US)",
    type: "Grant",
    location: "National",
    scope: "US",
    thesis: "Non-dilutive R&D for small businesses; agency-specific.",
    checkSize: "$50K–$2M phases",
    stage: "Pre-seed, Seed",
    website: "https://www.sbir.gov",
  },
  {
    name: "NIH SBIR",
    type: "Grant",
    location: "National",
    scope: "US",
    thesis: "Biomedical innovation; phased grants.",
    checkSize: "$150K–$2M+",
    stage: "Pre-clinical to early commercial",
    website: "https://seed.nih.gov",
  },
  {
    name: "Horizon Europe EIC",
    type: "Grant",
    location: "International",
    scope: "Europe",
    thesis: "Deep tech, climate, health; blended finance.",
    checkSize: "€500K–€15M",
    stage: "Seed to Series A",
    website: "https://eic.ec.europa.eu",
  },
  {
    name: "AWS Activate",
    type: "Grant",
    location: "International",
    scope: "Global",
    thesis: "Credits + support for startups building on AWS.",
    checkSize: "$1K–$100K credits",
    stage: "Pre-seed, Seed",
    website: "https://aws.amazon.com/activate",
  },
  {
    name: "Google for Startups",
    type: "Grant",
    location: "International",
    scope: "Global",
    thesis: "Cloud credits, mentoring, equity-free support.",
    checkSize: "Credits + programs",
    stage: "Pre-seed, Seed",
    website: "https://startup.google.com",
  },
  {
    name: "Naval Ravikant (AngelList syndicates)",
    type: "Angel",
    location: "International",
    scope: "US",
    thesis: "AngelList ecosystem; broad angel access via SPVs.",
    checkSize: "$25K–$500K SPVs",
    stage: "Pre-seed, Seed",
    website: "https://angel.co",
  },
  {
    name: "Fabrice Grinda (FCV)",
    type: "Angel",
    location: "International",
    scope: "Global",
    thesis: "Marketplaces, proptech, Latin America exposure.",
    checkSize: "$100K–$1M",
    stage: "Pre-seed, Seed",
    website: "https://fabricegrinda.com",
  },
  {
    name: "Jason Calacanis (LAUNCH)",
    type: "Angel",
    location: "National",
    scope: "US",
    thesis: "High-velocity seed; syndicate + podcast deal flow.",
    checkSize: "$25K–$250K",
    stage: "Pre-seed, Seed",
    website: "https://launch.co",
  },
  {
    name: "Republic (equity crowdfunding)",
    type: "Angel",
    location: "National",
    scope: "US",
    thesis: "Reg CF / equity crowdfunding for consumer and tech brands.",
    checkSize: "$100K–$5M raises",
    stage: "Pre-seed, Seed",
    website: "https://republic.com",
  },
  {
    name: "Local angel group (template)",
    type: "Angel",
    location: "Local",
    scope: "US",
    thesis: "Regional angels pooling diligence; sector varies.",
    checkSize: "$25K–$250K",
    stage: "Pre-seed, Seed",
    website: "https://www.angelcapitalassociation.org",
  },
  {
    name: "African Business Angels Network",
    type: "Angel",
    location: "Regional",
    scope: "Africa",
    thesis: "Pan-African angel education and deal sharing.",
    checkSize: "$10K–$200K",
    stage: "Pre-seed",
    website: "https://www.africanbusinessangelnetwork.com",
  },
  {
    name: "First Round Capital",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Operator-led seed; strong founder community.",
    checkSize: "$500K–$5M",
    stage: "Seed, Series A",
    website: "https://www.firstround.com",
  },
  {
    name: "Union Square Ventures",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Network-effect businesses; thesis-driven.",
    checkSize: "$1M–$15M",
    stage: "Seed to B",
    website: "https://www.usv.com",
  },
  {
    name: "Benchmark",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Concentrated, high-conviction early growth.",
    checkSize: "$5M–$50M",
    stage: "Series A–C",
    website: "https://www.benchmark.com",
  },
  {
    name: "Ribbit Capital",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Fintech everywhere; banking and payments.",
    checkSize: "$5M–$80M",
    stage: "Series A+",
    website: "https://www.ribbitcap.com",
  },
  {
    name: "Coatue",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Public + private crossover; growth tech.",
    checkSize: "$20M–$200M",
    stage: "Late seed to pre-IPO",
    website: "https://www.coatue.com",
  },
  {
    name: "Gaingels",
    type: "Angel",
    location: "National",
    scope: "US",
    thesis: "LGBTQ+/allied investors; inclusive cap tables.",
    checkSize: "$25K–$500K syndicates",
    stage: "Pre-seed, Seed",
    website: "https://www.gaingels.com",
  },
  {
    name: "Golden Seeds",
    type: "Angel",
    location: "National",
    scope: "US",
    thesis: "Women-led companies; education and healthcare tilt.",
    checkSize: "$50K–$1M",
    stage: "Seed",
    website: "https://goldenseeds.com",
  },
  {
    name: "Precursor Ventures",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Pre-seed specialist; software and hardware.",
    checkSize: "$100K–$750K",
    stage: "Pre-seed",
    website: "https://precursorvc.com",
  },
  {
    name: "Hustle Fund",
    type: "VC",
    location: "National",
    scope: "US",
    thesis: "Scrappy founders; very early checks.",
    checkSize: "$25K–$500K",
    stage: "Pre-seed",
    website: "https://www.hustlefund.vc",
  },
  {
    name: "Imaginary Ventures",
    type: "VC",
    location: "International",
    scope: "Global",
    thesis: "Consumer brands, commerce, next-gen retail.",
    checkSize: "$1M–$20M",
    stage: "Seed to B",
    website: "https://imaginaryventures.com",
  },
  {
    name: "Seedcamp",
    type: "Accelerator",
    location: "International",
    scope: "Europe",
    thesis: "European pre-seed; SaaS and marketplaces.",
    checkSize: "€200K–€500K",
    stage: "Pre-seed",
    website: "https://seedcamp.com",
  },
  {
    name: "Plug and Play",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "Corporate innovation programs; vertical accelerators.",
    checkSize: "$25K–$500K",
    stage: "Pre-seed, Seed",
    website: "https://www.plugandplaytechcenter.com",
  },
  {
    name: "MassChallenge",
    type: "Accelerator",
    location: "International",
    scope: "Global",
    thesis: "Zero-equity prizes; broad industry.",
    checkSize: "Non-dilutive awards",
    stage: "Pre-seed",
    website: "https://masschallenge.org",
  },
  {
    name: "Venture for Africa (VFA) fellows",
    type: "Grant",
    location: "Regional",
    scope: "Africa",
    thesis: "Talent placement + ecosystem (illustrative grant pattern).",
    checkSize: "Program-dependent",
    stage: "Pre-seed",
    website: "https://ventureforafrica.org",
  },
  {
    name: "Bill & Melinda Gates Foundation (strategic grants)",
    type: "Grant",
    location: "International",
    scope: "Global",
    thesis: "Global health, agriculture, education outcomes.",
    checkSize: "$500K–$50M+",
    stage: "Pilot to scale (non-equity)",
    website: "https://www.gatesfoundation.org",
  },
];

function normalize(s: string): string {
  return s.toLowerCase();
}

export type VentureMatchInput = {
  stage: number;
  name: string;
  stressMode?: string;
  industryVertical?: string | null;
};

/** Heuristic ranking — not personalized investment advice. */
export function matchInvestorsForVenture(venture: VentureMatchInput): FundingInvestor[] {
  const stage = venture.stage;
  const industry = normalize(venture.industryVertical ?? "");
  const name = normalize(venture.name);

  const scored = FUNDING_INVESTORS.map((inv) => {
    let score = 0;
    const st = normalize(inv.stage);
    const th = normalize(inv.thesis);

    if (stage <= 3) {
      if (st.includes("pre-seed") || st.includes("pre seed")) score += 4;
      if (inv.type === "Accelerator" || inv.type === "Grant") score += 2;
    } else if (stage <= 7) {
      if (st.includes("seed") && !st.includes("series")) score += 3;
      if (inv.type === "VC" && st.includes("seed")) score += 2;
    } else if (stage <= 11) {
      if (st.includes("series a") || st.includes("a–") || st.includes("a-")) score += 3;
      if (st.includes("series b")) score += 1;
    } else {
      if (st.includes("growth") || st.includes("series c") || st.includes("late")) score += 4;
    }

    if (industry && (th.includes(industry) || name.includes(industry))) score += 2;
    if (industry.includes("fintech") && th.includes("fintech")) score += 3;
    if (industry.includes("health") && (th.includes("health") || th.includes("bio"))) score += 3;
    if (industry.includes("climate") && th.includes("climate")) score += 3;

    if (venture.stressMode === "SURVIVAL" && (inv.type === "Grant" || inv.type === "Accelerator"))
      score += 1;

    return { inv, score };
  });

  scored.sort((a, b) => b.score - a.score);
  return scored.map((x) => x.inv);
}
